language: php
php:
  - '7.1'
  - '7.2'
  - '7.3'

before_install:
- composer require phpunit/phpunit:6.5.* php-coveralls/php-coveralls:2.1.*
- composer install --dev

script:
-

after_script:
- php vendor/bin/coveralls -v